---
- hosts: all
  gather_facts: False
  collections:
    - dellemc.powerstore

  tasks:
  - name: Include the create host_vg_hg task
    include_tasks: ./modules/create_host_with_iqn.yml

  - name: Get the details of the array
    dellemc_powerstore_gatherfacts:
      array_ip: "{{array_ip}}"
      user: "{{user}}"
      password: "{{password}}"
      verifycert: "{{verifycert}}"
      gather_subset:
        - vol
    register: subset_result

  - name: Print out the details of the array
    debug:
      var: subset_result

  - name: Get list of volumes
    dellemc_powerstore_gatherfacts:
      array_ip: "{{array_ip}}"
      verifycert: "{{verifycert}}"
      user: "{{user}}"
      password: "{{password}}"
      gather_subset:
        - vol
    register: volume_result

  - name: Print out the details of the volumes
    debug:
      var: volume_result
