---
- hosts: localhost
  vars:
    ansible_connection: local
    array_ip: 192.168.1.30
    user: admin
    password: P@ssw0rd!
    verifycert: False
  collections:
    - dellemc.powerstore

  tasks:

  - name: Get the details of the array
    dellemc_powerstore_gatherfacts:
      array_ip: "{{array_ip}}"
      user: "{{user}}"
      password: "{{password}}"
      verifycert: "{{verifycert}}"
      gather_subset:
        - vol
    register: subset_result


  - name: Print out the details of the array
    debug:
      var: subset_result

  - name: Get list of volumes
    dellemc_powerstore_gatherfacts:
      array_ip: "{{array_ip}}"
      verifycert: "{{verifycert}}"
      user: "{{user}}"
      password: "{{password}}"
      gather_subset:
        - vol
    register: volume_result

  - name: Print out the details of the volumes
    debug:
      var: volume_result
