---
- hosts: all
  connection: local
  gather_facts: False
  collections:
    - dellemc.powerstore

  tasks:
  - name: Create a volume snapshot on PowerStore
    dellemc_powerstore_snapshot:
      array_ip: "{{array_ip}}"
      verifycert: False
      user: "{{user}}"
      password: "{{password}}"
      snapshot_name: snap_volume_001
      volume: volume_001
      description: "This is a snapshot created by an ansible playbook"
      desired_retention: 7
      retention_unit: days
      state: present

  - name: Get details of an existing snapshot rule by name
    dellemc_powerstore_snapshotrule:
      array_ip: "{{array_ip}}"
      verifycert: False
      user: "{{user}}"
      password: "{{password}}"
      name: snap_volume_001
      state: "present"
    register: snapshot_rule


  - name: Display list of of snapshot rules
    debug:
      var: snapshot_rule
