---
- hosts: all
  connection: local
  gather_facts: True
  collections:
    - community.general.open_iscsi

  tasks:
  - name: Perform a discovery on and show available target nodes
    shell: cat /etc/iscsi/initiatorname.iscsi | awk -F"=" '{print $2}'
    register: iscsi

  - name: Display list of volumes
    debug:
      var: iscsi
