---
- hosts: all
  connection: local
  gather_facts: False
  collections:
    - dellemc.powerstore

  tasks:
  - name: Create host group with hosts using host name
    dellemc_powerstore_hostgroup:
      array_ip: "{{array_ip}}"
      verifycert: False
      user: "{{user}}"
      password: "{{password}}"
      hostgroup_name: host_group_001
      hosts: host_001
      host_state: 'present-in-group'
      state: 'present'

  - name: Get list of host groups
    dellemc_powerstore_gatherfacts:
      array_ip: "{{array_ip}}"
      verifycert: False
      user: "{{user}}"
      password: "{{password}}"
      gather_subset:
        - hg
    register: host_group

  - name: Display list of volumes
    debug:
      var: host_group
