---
- hosts: all
  connection: local
  gather_facts: False
  collections:
    - dellemc.powerstore

  tasks:
  - name: Create volume group without protection policy
    dellemc_powerstore_volumegroup:
      array_ip: "{{array_ip}}"
      verifycert: False
      user: "{{user}}"
      password: "{{password}}"
      vg_name: volume_group_001
      description: "This volume group is for ansible"
      state: "present"

  - name: Get list of volume groups
    dellemc_powerstore_gatherfacts:
      array_ip: "{{array_ip}}"
      verifycert: False
      user: "{{user}}"
      password: "{{password}}"
      gather_subset:
        - vg
    register: volume_group

  - name: Display list of volumes groups
    debug:
      var: volume_group
