---
- hosts: all
  connection: local
  gather_facts: False
  collections:
    - dellemc.powerstore

  tasks:

  - name: Create stand-alone volume
    dellemc_powerstore_volume:
      array_ip: "{{array_ip}}"
      verifycert: False
      user: "{{user}}"
      password: "{{password}}"
      vol_name: 'volume_001'
      size: 1
      cap_unit: GB
      state: 'present'

  - name: Get list of volumes
    dellemc_powerstore_gatherfacts:
      array_ip: "{{array_ip}}"
      verifycert: False
      user: "{{user}}"
      password: "{{password}}"
      gather_subset:
        - vol
    register: volumes

  - name: Display list of volumes
    debug:
      var: volumes
